'use strict';

/**
 * Generates and persists the per-install compose env file.
 *
 * The Neo4j password is randomized once and then REUSED on every later launch —
 * the password is baked into the neo4j_data volume the first time the DB starts,
 * so regenerating it would lock the app out of its own database. We therefore
 * read an existing desktop.env and only fill in what's missing.
 */

const fs = require('fs');
const crypto = require('crypto');
const paths = require('./paths');

function randomPassword() {
  // URL/alphanumeric-safe, no '/' (NEO4J_AUTH splits on '/').
  return crypto.randomBytes(24).toString('base64').replace(/[^A-Za-z0-9]/g, '').slice(0, 28);
}

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq < 0) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

function serialize(vars) {
  const header =
    '# Generated by EM Knowledge Assistant. Do not edit by hand.\n' +
    '# The Neo4j password is baked into the database volume on first launch;\n' +
    '# changing it here will break authentication.\n';
  return header + Object.entries(vars).map(([k, v]) => `${k}=${v}`).join('\n') + '\n';
}

/**
 * Ensure desktop.env exists and contains a stable password plus the current
 * host paths / image version. Returns { path, vars }.
 * @param {{appVersion:string}} opts
 */
function ensureEnvFile({ appVersion }) {
  const envPath = paths.envFilePath();
  const existing = fs.existsSync(envPath) ? parseEnv(fs.readFileSync(envPath, 'utf8')) : {};

  const password = (existing.NEO4J_AUTH && existing.NEO4J_AUTH.split('/')[1]) || randomPassword();

  const vars = {
    NEO4J_AUTH: `neo4j/${password}`,
    DB_URI: 'bolt://neo4j:7687',
    APP_VERSION: appVersion,
    // Docker Compose needs a forward-slashed absolute path even on Windows.
    PROJECT_DATA_DIR: paths.projectDataDir().replace(/\\/g, '/'),
  };

  fs.mkdirSync(paths.userDataDir(), { recursive: true });
  fs.writeFileSync(envPath, serialize(vars), 'utf8');
  return { path: envPath, vars };
}

module.exports = { ensureEnvFile, parseEnv };
