'use strict';

/**
 * Generates and persists the per-install env file the native supervisor reads.
 *
 * The Neo4j password is randomized once and then REUSED on every later launch —
 * it is set on the native store via `neo4j-admin dbms set-initial-password` on
 * first run and baked into the data dir, so regenerating it would lock the app
 * out of its own database. We therefore read an existing desktop.env and only
 * fill in what's missing.
 */

const fs = require('fs');
const crypto = require('crypto');
const paths = require('./paths');

function randomPassword() {
  // URL/alphanumeric-safe, no '/' (NEO4J_AUTH splits on '/').
  return crypto.randomBytes(24).toString('base64').replace(/[^A-Za-z0-9]/g, '').slice(0, 28);
}

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq < 0) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

function serialize(vars) {
  const header =
    '# Generated by EM Knowledge Assistant. Do not edit by hand.\n' +
    '# The Neo4j password is set on the native store on first launch;\n' +
    '# changing it here will break authentication.\n';
  return header + Object.entries(vars).map(([k, v]) => `${k}=${v}`).join('\n') + '\n';
}

/**
 * Ensure desktop.env exists and holds a stable password plus the values the
 * native supervisor passes to the child processes. Returns { path, vars }.
 *
 * `appVersion` is accepted for call-site compatibility but no longer written —
 * there is no prebuilt image tag to pin now that the API runs natively.
 * @param {{appVersion?:string}} [opts]
 */
function ensureEnvFile({ appVersion } = {}) {
  void appVersion;
  const envPath = paths.envFilePath();
  const existing = fs.existsSync(envPath) ? parseEnv(fs.readFileSync(envPath, 'utf8')) : {};

  const password = (existing.NEO4J_AUTH && existing.NEO4J_AUTH.split('/')[1]) || randomPassword();

  const vars = {
    NEO4J_AUTH: `neo4j/${password}`,
    // Native: the API reaches Neo4j over loopback (was bolt://neo4j:7687 under
    // the compose network).
    DB_URI: 'bolt://127.0.0.1:7687',
    // Ingestion root + /files citation base. Forward slashes even on Windows so
    // it matches the forward-slashed File.filepath stored in the graph.
    DATA_ROOT: paths.projectDataDir().replace(/\\/g, '/'),
  };

  fs.mkdirSync(paths.userDataDir(), { recursive: true });
  fs.writeFileSync(envPath, serialize(vars), 'utf8');
  return { path: envPath, vars };
}

module.exports = { ensureEnvFile, parseEnv };
