'use strict';

/**
 * Unit tests for lib/envfile.js — the per-install desktop.env.
 *
 * The invariant worth a test is password stability. The Neo4j password is set on
 * the native store by `neo4j-admin dbms set-initial-password` on first run and
 * baked into the data dir, so if ensureEnvFile ever regenerated it the app would
 * lock itself out of its own database on the next launch — with a graph the user
 * cannot rebuild without the whole ingest/enrich pipeline.
 *
 * Also pins parseEnv, which supervisor.js uses to read that file back into the
 * child processes' environment.
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');

const { stubElectron } = require('./electron-stub');

const { userData } = stubElectron(); // lib/envfile.js -> lib/paths.js

const { ensureEnvFile, parseEnv } = require('../lib/envfile');

test.beforeEach(() => {
  fs.rmSync(path.join(userData, 'desktop.env'), { force: true });
});

// --- parseEnv ---------------------------------------------------------------

test('parseEnv reads KEY=VALUE pairs', () => {
  assert.deepEqual(parseEnv('A=1\nB=two\n'), { A: '1', B: 'two' });
});

test('parseEnv skips comments and blank lines', () => {
  const text = '# a comment\n\n  \nA=1\n  # indented comment\nB=2\n';
  assert.deepEqual(parseEnv(text), { A: '1', B: '2' });
});

test('parseEnv handles CRLF, as written on Windows', () => {
  assert.deepEqual(parseEnv('A=1\r\nB=2\r\n'), { A: '1', B: '2' });
});

test('parseEnv keeps everything after the first = (URIs contain them)', () => {
  const vars = parseEnv('DB_URI=bolt://127.0.0.1:7687\nQ=a=b=c\n');
  assert.equal(vars.DB_URI, 'bolt://127.0.0.1:7687');
  assert.equal(vars.Q, 'a=b=c');
});

test('parseEnv trims surrounding whitespace on keys and values', () => {
  assert.deepEqual(parseEnv('  A = 1 \n'), { A: '1' });
});

test('parseEnv ignores lines with no =', () => {
  assert.deepEqual(parseEnv('garbage\nA=1\n'), { A: '1' });
});

test('parseEnv round-trips what ensureEnvFile writes', () => {
  const { path: p, vars } = ensureEnvFile();
  assert.deepEqual(parseEnv(fs.readFileSync(p, 'utf8')), vars);
});

// --- ensureEnvFile ----------------------------------------------------------

test('ensureEnvFile writes the values the native children need', () => {
  const { path: p, vars } = ensureEnvFile();

  assert.ok(fs.existsSync(p));
  assert.equal(vars.DB_URI, 'bolt://127.0.0.1:7687');
  assert.match(vars.NEO4J_AUTH, /^neo4j\/[A-Za-z0-9]+$/);
  assert.ok(vars.DATA_ROOT.endsWith('project_data'));
});

test('DATA_ROOT is forward-slashed so it matches File.filepath in the graph', () => {
  const { vars } = ensureEnvFile();
  assert.equal(vars.DATA_ROOT.includes('\\'), false, `got ${vars.DATA_ROOT}`);
});

test('the generated password survives a second call', () => {
  const first = ensureEnvFile().vars.NEO4J_AUTH;
  const second = ensureEnvFile().vars.NEO4J_AUTH;
  assert.equal(second, first, 'regenerating it would lock the app out of its own store');
});

test('an existing password is reused even when other values are rewritten', () => {
  const p = path.join(userData, 'desktop.env');
  fs.mkdirSync(userData, { recursive: true });
  fs.writeFileSync(p, 'NEO4J_AUTH=neo4j/PreexistingSecret123\nSTALE_KEY=drop-me\n', 'utf8');

  const { vars } = ensureEnvFile();

  assert.equal(vars.NEO4J_AUTH, 'neo4j/PreexistingSecret123');
  assert.equal(vars.STALE_KEY, undefined, 'compose-era keys are not carried forward');
  assert.equal(parseEnv(fs.readFileSync(p, 'utf8')).STALE_KEY, undefined);
});

test('the password contains no / so NEO4J_AUTH stays splittable', () => {
  // connection.py splits NEO4J_AUTH on '/', so a '/' in the password silently
  // truncates the credential.
  for (let i = 0; i < 25; i++) {
    fs.rmSync(path.join(userData, 'desktop.env'), { force: true });
    const password = ensureEnvFile().vars.NEO4J_AUTH.split('/')[1];
    assert.match(password, /^[A-Za-z0-9]+$/);
    assert.ok(password.length >= 20, `too short: ${password.length}`);
  }
});

test('the file warns against hand-editing', () => {
  const { path: p } = ensureEnvFile();
  assert.match(fs.readFileSync(p, 'utf8'), /^# Generated by EM Knowledge Assistant/);
});

test('ensureEnvFile creates userData when it does not exist yet', () => {
  const fresh = path.join(os.tmpdir(), `emb-fresh-${Date.now()}`);
  const { userData: dir } = stubElectron({ userData: fresh });
  assert.equal(fs.existsSync(dir), false);

  // Re-require through a clean cache so lib/paths picks up the new stub.
  delete require.cache[require.resolve('../lib/paths')];
  delete require.cache[require.resolve('../lib/envfile')];
  const { path: p } = require('../lib/envfile').ensureEnvFile();

  assert.ok(fs.existsSync(p));
  assert.ok(p.startsWith(fresh));
});
